package gfx;

public enum Sprite {
    BEAM, LADDER,
    PLAYER_IDLE_LEFT, PLAYER_IDLE_RIGHT,
    PLAYER_JUMP_LEFT, PLAYER_JUMP_RIGHT,
    PLAYER_CLIMBING_UP1, PLAYER_CLIMBING_UP2,
    PLAYER_STANDING,
    PLAYER_FALL_RIGHT, PLAYER_FALL_LEFT,
    LOGO, MENU_LIST,
    BARREL_STANDING,
    DK_IDLE, DK_LEFT, DK_RIGHT,
    PRINCESS
}
